class Questions {
  List<String> questionsDare = [
    "Telefonu havaya atıp yakalamaya çalış.",
    "En son mesajlaştığın arkadaşına ondan hoşlandığını söyle.",
    "3 dk boyunca konuşmamaya çalış.",
    "En sevdiğin şarkıyı söyle.",
    "10 mekik çek.",
    "Anlatmaktan utandığın bir anını bizimle paylaş.",
    "Senden sonra sırası gelecek arkadaşına sana bir tokat atmasına izin ver.",
    "3 farklı hayvanı taklit et.",
    "Bütün arkadaşlarından para toplamaya çalış ve o parayla mama alıp sokak hayvanlarına ver.",
    "Balerin dansı yapmaya çalış.",
    "Odadaki herkese sarıl ve onu sevdiğini söyle.",
    "Sosyal medya hesabına 3 dk silmemek şartıyla saçma bir fotoğrafını paylaş.",
    "Sürekli doğruluk seçen bir arkadaşını seç ve onun bir sonraki tur cesaret seçmesini sağla.",
    'Sana gelen en son mesajı sesli oku.',
    'Gözlerin bağlı, sadece dokunarak bir arkadaşını tanı.',
    'Ellerini kullanmadan bir elma ye.',
    'Bir çay bardağı sirke iç.',
    'Pencereyi açıp yoldan geçenlere “maskelerinizi takın” diye yüksek sesle bağır.',
    'Yanındaki arkadaşının sana absürt bir makyaj yapmasına izin ver.',
    'Sana söylenmiş çok önemli bir sırrı bizimle paylaş.',
    'Bir bütün çiğ soğan ye.',
    'Yanındaki arkadaşının alnına bir şeyler yazmasına izin ver.',
    'Oyunu iki tur boyunca gözlerin bağlı oyna.',
    'Ağzına bir buz alıp, komple bitene kadar ağzını açma.',
    'Mezdeke eşliğinde oryantal dans et.',
    'İnstagram hesabından on kişiyi sil.',
    'Bir sihirbazlık numarası yapmaya çalış.',
    'Arka arkaya dinlenmeden beş bardak su iç.',
    'Üç dakika boyunca bir arkadaşına masaj yap.',
    'Gruptan seçilen birini gözlerin bağlı kokusundan tanımaya çalış.',
    'Banyoya gidip tüm kıyafetlerini ters giyip geri gel.',
    'Kafanın üzerine konan kitapları düşürmeden grup etrafında sekiz tur at.',
    'Açılan Hint müziği ile dans et.',
    'Gözlerini kırpmadan 30 saniye yanındaki arkadaşının gözlerine bak.',
    'Gözünden yaş gelene kadar ağlamaya çalış.',
    'Gözlerini kırpmadan 30 saniye yanındaki arkadaşının gözlerine bak.',
    'Gözünden yaş gelene kadar ağla.',
    'Odanın bir ucundan diğerine ellerin üzerinde yürü.',
    'Ailene telefon et ve neden işten (üniversiteden ya da okuldan da olabilir) atıldığınızı anlatın.',
    'Eğer erkekse makyaj yapmasını isteyin. Eğer kızsa makyajını silmesini isteyin.',
    '1 dakika boyunca hiç müzik olmadan dans edin.',
    'Odada ki herkesin koltuk altını koklayın.',
    'Kafanın üstünde iki yumurta kır.',
    'Önümüzdeki 5 dakika içinde birinin hayvanı olun.',
    'Elbiselerinizle bir duş alın.',
    'Size bir tokat atmak için gruptan birini seçin.',
    'Başkasının dişlerini fırçala.',
    'Komşunun evine git ve muz iste.',
    'Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin',
    '3 dakika boyunca stand-up gösteri yap.',
    "Anlatmaktan utandığın bir özelliğini bizimle paylaş.",
    "Arkadaşlarının tarayıcı geçmişini incelemelerine izin ver",
    "Whatsapp mesajlarını görmezden geldiğin bir arkadaşını söyle ve ondan özür dile.",
    "Fake hesabından gerçek kimliğini açıkla. Fake hesabın yoksa sıranı geçebilirsin.",
    "3 kişi 'seni seviyorum' mesajı yolla ve 30 dk boyunca bunun bir şaka olduduğunu söyleyeme.",
    "Hayallerindeki partnerini bize tanımla.",
    'Önümüzdeki 5 dakika boyunca söylediğin her şeyden sonra “mee” diyeceksin deyin',
    '3 dakika boyunca stand-up gösteri yap.',
    'Ayak parmaklarından birini em. Eğer yapamazsan başkasının parmağını emeceksin.',
  ];

  List<String> questionsTruth = [
    "Eski sevgilini özlüyor musun?",
    "En çok kıskandığın arkadaşın kim?",
    "İlk görüşte aşka inanır mısın?",
    "En sevmediğin özelliğin nedir?",
    "Vücudunun en çok hangi kısmını seviyorsun?",
    "Desteklediğin spor klubünü değiştirme şansın olsaydı hangisini seçerdin?",
    "En çok beğendiğin 5 karşı cins arkadaşını say? Onları sırala.",
    "Zengin olsaydın ilk önce yapacağın şey ne olurdu?",
    "Kendi cinsiyetinden birisininde en çok kıskandığın özellik?",
    "Aşka inanıyor musunuz?",
    "Ailene söylediğin en büyük yalan nedir?",
    "Senden bir önceki arkadaşının en sevmediğin özelliği nedir?",
    "Sevdiğin birini hiç aldattın mı?",
    "Daha önce hoşlanmadığın birisiyle sevgili oldun mu?",
    "Bu odada en güzel gülen kim?",
    "Hayatta yaptığın en büyük kötülük nedir?",
    "Anne babana söylediğin en büyük yalan nedir?",
    "En büyük korkun nedir?",
    "Ölmesini istediğin birini söyler misin?",
    "Dini inanışını değiştirmeyi hiç düşündün mü?",
    "Senin sevdiğin ama çoğu insanın sevmediği bir şey hakkında sevmemiş numarası yaptın mı, ne olduğunu bizimle paylaş?",
    "Bu odada en kötü giyinen kişi kim?",
    "Bir gün karşı cins olarak uyansan ilk yapacağın iş nedir?",
    "Akrabalarından en sevmediğin kişi kimdir?",
    "Bir yangın anında hepimiz aynı binada kalsak buradakilerden en son kimi kurtarırdın?",
    "Hiç batıl inancın var mı, nedir?",
    "Gizli aşkın kim?",
    "Hala yaptığın en çocukça şey nedir?",
    "Bu odadaki birinin bir fiziksel özelliğine sahip olsaydınız, bu ne olurdu?",
    "Kimsenin senin hakkında bilmediği bir şey nedir?",
    "Sahip olduğunuz en iğrenç alışkanlık nedir?",
    "En son ne zaman ağladın?",
    "Kaç tane sevgilin oldu?",
    "Ünlü biriyle çıkabilseydin, kim olurdu?",
    "Eğer görünmez olsaydın, bu odadan kimi gözetlemek isterdin?",
    "Sevgiline hiç yalan söyledin mi, bizimle paylaş?",
    "En iyi arkadaşının iyi ve kötü özellikleri say",
    "Bu odadaki insanlardan, kiminle çıkardın?",
    "Karşı cinsi etkilemek için yaptığın en saçma şey nedir?",
    "En son kime çıkma teklifiği ettin ve onun cevabı ne oldu?",
    "Odanın her bir kişi hakkında bir tane olumlu, bir tane olumsuz şey söyleyin.",
    "Bu odada biriyle evlenmek zorunda kalsan kim olurdu?",
    "Hiç sevgili bulmak için internet sitesi kullandın mı?",
    "En büyük korkun nedir?",
    "Bir buluşmada yaptığın en utanç verici davranışın nedir?",
    "En son hangi yalanı söyledin?",
    "Hayalindeki kariyer nedir?",
    "Dinlemekten en çok utandığın şarkı hangisidir?",
    "Duş almadan geçirdiğin en uzun süre ne kadardı?",
    "Hayatının geri kalanı boyunca sadece bir tane şarkı dinleme hakkın olsa bu hangi şarkı olurdu?",
    "Yediğin en iğrenç yiyecek nedir?",
    "Yaptığın illegal şey nedir?",
    "Sadece bir kerelik zamanda geri gitme şansın olsa hangi zamana gidip ne yapardın?",
    "Kendin hakkında başka kimsenin bilmediği özelliğin nedir?",
    "İlk buluşmada kesinlikle yapılmaması gereken şey nedir?",
    "En uzun ilişkin ne kadar sürdü ve neden bitti?",
    "Sarışın mı esmer mi?",
    "Friendzone'a yakalansaydın ne yapardın?",
  ];
}
